# Generated by Django 3.2.9 on 2021-11-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='Imagem',
            field=models.ImageField(upload_to='assets/images'),
        ),
    ]
