# Generated by Django 3.2.9 on 2021-11-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_manager', '0002_alter_portfolioitem_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='Imagem',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(default='', upload_to='assets/images', verbose_name='image'),
            preserve_default=False,
        ),
    ]
