# Generated by Django 3.2.9 on 2021-11-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_manager', '0003_auto_20211121_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(upload_to='portfolio/images', verbose_name='image'),
        ),
    ]
