# Generated by Django 3.2.9 on 2021-11-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=255, verbose_name='Cliente')),
                ('time', models.TimeField(verbose_name='Horário')),
                ('services', models.ManyToManyField(to='shared.Service', verbose_name='Serviços')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
